<h5>US Census Population 2020 to 2025 Extraction</h5>
<h6></h6>

In [44]:
import pandas as pd
import numpy as np
import re #import regular expressions module (set of string that matches the criteria)
from collections import defaultdict
import us #import us library
pop_census1 = pd.read_csv("Pop_2010to2019.csv")
pop_census2 = pd.read_csv("USCensus_2020_2024.csv")

In [45]:
#inspecting data using Python
#display data first 5 rows
pop_census1.head()
pop_census2.head()

,SUMLEV,REGION,DIVISION,STATE,NAME,ESTIMATESBASE2020,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,...,NRANK_NPCHG2020,NRANK_NPCHG2021,NRANK_NPCHG2022,NRANK_NPCHG2023,NRANK_NPCHG2024,NRANK_PPCHG2020,NRANK_PPCHG2021,NRANK_PPCHG2022,NRANK_PPCHG2023,NRANK_PPCHG2024
0,10,0,0,0,United States,331515736,331577720,332099760,334017321,336806231,...,X,X,X,X,X,X,X,X,X,X
1,20,1,0,0,Northeast Region,57617706,57431458,57252533,57159597,57398303,...,4,4,4,4,3,4,4,4,3,3
2,30,1,1,0,New England,15122011,15057350,15118145,15175633,15263573,...,8,4,5,9,9,9,4,5,5,4
3,30,1,2,0,Middle Atlantic,42495695,42374108,42134388,41983964,42134730,...,9,8,9,6,5,8,8,9,7,6
4,20,2,0,0,Midwest Region,68998970,68984258,68872831,68903297,69186401,...,3,3,3,3,4,3,3,3,4,4

In [7]:
#checking for missing values
#pop_census1.isnull().sum()
#pop_census2.isnull().sum()
#no null

In [46]:
#view all columns
print(pop_census1.columns.tolist())
print(pop_census2.columns.tolist())

['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'NAME', 'CENSUS2010POP', 'ESTIMATESBASE2010', 'POPESTIMATE2010', 'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2015', 'POPESTIMATE2016', 'POPESTIMATE2017', 'POPESTIMATE2018', 'POPESTIMATE2019', 'NPOPCHG_2010', 'NPOPCHG_2011', 'NPOPCHG_2012', 'NPOPCHG_2013', 'NPOPCHG_2014', 'NPOPCHG_2015', 'NPOPCHG_2016', 'NPOPCHG_2017', 'NPOPCHG_2018', 'NPOPCHG_2019', 'BIRTHS2010', 'BIRTHS2011', 'BIRTHS2012', 'BIRTHS2013', 'BIRTHS2014', 'BIRTHS2015', 'BIRTHS2016', 'BIRTHS2017', 'BIRTHS2018', 'BIRTHS2019', 'DEATHS2010', 'DEATHS2011', 'DEATHS2012', 'DEATHS2013', 'DEATHS2014', 'DEATHS2015', 'DEATHS2016', 'DEATHS2017', 'DEATHS2018', 'DEATHS2019', 'NATURALINC2010', 'NATURALINC2011', 'NATURALINC2012', 'NATURALINC2013', 'NATURALINC2014', 'NATURALINC2015', 'NATURALINC2016', 'NATURALINC2017', 'NATURALINC2018', 'NATURALINC2019', 'INTERNATIONALMIG2010', 'INTERNATIONALMIG2011', 'INTERNATIONALMIG2012', 'INTERNATIONALMIG2013', 'INTERNATIONALMIG2014', 'INTERNATIONALMIG2015', 'INTERNATIONALMIG2016', 'INTERNATIONALMIG2017', 'INTERNATIONALMIG2018', 'INTERNATIONALMIG2019', 'DOMESTICMIG2010', 'DOMESTICMIG2011', 'DOMESTICMIG2012', 'DOMESTICMIG2013', 'DOMESTICMIG2014', 'DOMESTICMIG2015', 'DOMESTICMIG2016', 'DOMESTICMIG2017', 'DOMESTICMIG2018', 'DOMESTICMIG2019', 'NETMIG2010', 'NETMIG2011', 'NETMIG2012', 'NETMIG2013', 'NETMIG2014', 'NETMIG2015', 'NETMIG2016', 'NETMIG2017', 'NETMIG2018', 'NETMIG2019', 'RESIDUAL2010', 'RESIDUAL2011', 'RESIDUAL2012', 'RESIDUAL2013', 'RESIDUAL2014', 'RESIDUAL2015', 'RESIDUAL2016', 'RESIDUAL2017', 'RESIDUAL2018', 'RESIDUAL2019', 'RBIRTH2011', 'RBIRTH2012', 'RBIRTH2013', 'RBIRTH2014', 'RBIRTH2015', 'RBIRTH2016', 'RBIRTH2017', 'RBIRTH2018', 'RBIRTH2019', 'RDEATH2011', 'RDEATH2012', 'RDEATH2013', 'RDEATH2014', 'RDEATH2015', 'RDEATH2016', 'RDEATH2017', 'RDEATH2018', 'RDEATH2019', 'RNATURALINC2011', 'RNATURALINC2012', 'RNATURALINC2013', 'RNATURALINC2014', 'RNATURALINC2015', 'RNATURALINC2016', 'RNATURALINC2017', 'RNATURALINC2018', 'RNATURALINC2019', 'RINTERNATIONALMIG2011', 'RINTERNATIONALMIG2012', 'RINTERNATIONALMIG2013', 'RINTERNATIONALMIG2014', 'RINTERNATIONALMIG2015', 'RINTERNATIONALMIG2016', 'RINTERNATIONALMIG2017', 'RINTERNATIONALMIG2018', 'RINTERNATIONALMIG2019', 'RDOMESTICMIG2011', 'RDOMESTICMIG2012', 'RDOMESTICMIG2013', 'RDOMESTICMIG2014', 'RDOMESTICMIG2015', 'RDOMESTICMIG2016', 'RDOMESTICMIG2017', 'RDOMESTICMIG2018', 'RDOMESTICMIG2019', 'RNETMIG2011', 'RNETMIG2012', 'RNETMIG2013', 'RNETMIG2014', 'RNETMIG2015', 'RNETMIG2016', 'RNETMIG2017', 'RNETMIG2018', 'RNETMIG2019']
['SUMLEV', 'REGION', 'DIVISION', 'STATE', 'NAME', 'ESTIMATESBASE2020', 'POPESTIMATE2020', 'POPESTIMATE2021', 'POPESTIMATE2022', 'POPESTIMATE2023', 'POPESTIMATE2024', 'NPOPCHG_2020', 'NPOPCHG_2021', 'NPOPCHG_2022', 'NPOPCHG_2023', 'NPOPCHG_2024', 'PPOPCHG_2020', 'PPOPCHG_2021', 'PPOPCHG_2022', 'PPOPCHG_2023', 'PPOPCHG_2024', 'NRANK_ESTBASE2020', 'NRANK_POPEST2020', 'NRANK_POPEST2021', 'NRANK_POPEST2022', 'NRANK_POPEST2023', 'NRANK_POPEST2024', 'NRANK_NPCHG2020', 'NRANK_NPCHG2021', 'NRANK_NPCHG2022', 'NRANK_NPCHG2023', 'NRANK_NPCHG2024', 'NRANK_PPCHG2020', 'NRANK_PPCHG2021', 'NRANK_PPCHG2022', 'NRANK_PPCHG2023', 'NRANK_PPCHG2024']

In [49]:
#drop columns
pop_census2_1 = pop_census2.drop(columns=pop_census2.loc[:, 'SUMLEV':'STATE'].columns)
pop_census2_1 = pop_census2_1.drop(columns=pop_census2_1.loc[:, 'NPOPCHG_2020':'NRANK_PPCHG2024'].columns)
pop_census2_1 = pop_census2_1.drop(columns='ESTIMATESBASE2020')
pop_census2_1.head()

,NAME,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024
0,United States,331577720,332099760,334017321,336806231,340110988
1,Northeast Region,57431458,57252533,57159597,57398303,57832935
2,New England,15057350,15118145,15175633,15263573,15386085
3,Middle Atlantic,42374108,42134388,41983964,42134730,42446850
4,Midwest Region,68984258,68872831,68903297,69186401,69596584

In [50]:
#drop columns for pop_census1
pop_census1_1 = pop_census1.drop(columns=pop_census1.loc[:, 'SUMLEV':'STATE'].columns)
pop_census1_1 = pop_census1_1.drop(columns=pop_census1_1.loc[:, 'NPOPCHG_2010':'RNETMIG2019'].columns)
pop_census1_1 = pop_census1_1.drop(columns=pop_census1_1.loc[:, 'CENSUS2010POP':'POPESTIMATE2011'].columns)
pop_census1_1.head()

,NAME,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019
0,United States,313830990,315993715,318301008,320635163,322941311,324985539,326687501,328239523
1,Northeast Region,55775216,55901806,56006011,56034684,56042330,56059240,56046620,55982803
2,Midwest Region,67336743,67560379,67745167,67860583,67987540,68126781,68236628,68329004
3,South Region,117241208,118364400,119624037,120997341,122351760,123542189,124569433,125580448
4,West Region,73477823,74167130,74925793,75742555,76559681,77257329,77834820,78347268

In [56]:
#drop first 5 rows
#pop_census1_2 = pop_census1_1.iloc[5:]
pop_census1_2.shape

#pop_census2_2 = pop_census2_1.iloc[14:]
pop_census2_2.shape

(52, 6)

In [59]:
#remove DC and PR
#pop_census1_3 = pop_census1_2[~pop_census1_2['NAME'].isin(['District of Columbia','Puerto Rico'])]
#pop_census1_3.shape

#pop_census2_3 = pop_census2_2[~pop_census2_2['NAME'].isin(['District of Columbia','Puerto Rico'])]
pop_census2_3.shape

(50, 6)

In [60]:
#merge both dataset together
merged_census = pd.merge(pop_census1_3, pop_census2_3, on='NAME', how='inner')

In [61]:
merged_census.head()

,NAME,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,POPESTIMATE2019,POPESTIMATE2020,POPESTIMATE2021,POPESTIMATE2022,POPESTIMATE2023,POPESTIMATE2024
0,Alabama,4815588,4830081,4841799,4852347,4863525,4874486,4887681,4903185,5033094,5049196,5076181,5117673,5157699
1,Alaska,730443,737068,736283,737498,741456,739700,735139,731545,733017,734420,734442,736510,740133
2,Arizona,6554978,6632764,6730413,6829676,6941072,7044008,7158024,7278717,7187135,7274078,7377566,7473027,7582384
3,Arkansas,2952164,2959400,2967392,2978048,2989918,3001345,3009733,3017804,3014546,3026870,3047704,3069463,3088354
4,California,37948800,38260787,38596972,38918045,39167117,39358497,39461588,39512223,39521958,39142565,39142414,39198693,39431263

In [63]:
merged_census.to_csv('Clean_USCensus_2012to2024.csv', index=False)